### ISSUE TITLE
[Enhancement Request] Allow overriding the image name variable restriction for render and inspect

### ISSUE THREAD

**Issue by jhrabi** [docker/app#530] opened 2019-05-01 01:10 UTC
Starting in v0.8.0-beta1, the following restriction has been added:

> Image names and tags can no longer be templated

Obviously this now results in seeing something similar to this when trying to use my current dockerapp files:

`vote: variables are not allowed in the service's image field. Found: '${VOTING_IMAGE}/examplevotingapp_vote'`

My understanding from some discussion at DockerCon is that this was specifically added to support CNAB requirements for recreatable deployments for images. This has caused a breaking change for me where we had parameters used to allow identical configurations to be used for different versions of similar images, thus allowing us not to have to generate multiple configurations.

I understand that if there are CNAB requirements that this decision is likely not going to be reversed. However, for my specific requirement, an override of some type (even an experimental feature) to allow this restriction to be overridden for a render or inspect would help overcome this.

**Comment by ijc** [comment] 2019-05-01 08:24
Thanks for the suggestion. I think this is a duplicate of #508 where possible solutions to this requirement are being discussed.

**Closed by ijc** 2019-05-01 08:24 UTC
